//
//  GitRepoWorker.swift
//  Assignment1
//
//  Created by A667271 A667271 on 31/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class GitRepoWorker
{
  func doSomeWork()
  {
  }
}
