//
//  GitRepoModels.swift
//  Assignment1
//
//  Created by A667271 A667271 on 31/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import Foundation

struct All {
    let count: Int
    let all: [Repository]
}

extension All: Decodable {
    enum CodingKeys: String, CodingKey {
        case count = "total_count"
        case all = "items"
    }
}

struct Repository {
    let id: Int
    let name: String
    let fullName: String
    let owner: Owner
}

extension Repository: Decodable {
    enum CodingKeys: String, CodingKey {
        case id
        case name
        case fullName = "full_name"
        case owner
    }
}

struct Owner {
    let avatarURL: String
}

extension Owner: Decodable {
    enum CodingKeys: String, CodingKey {
        case avatarURL = "avatar_url"
    }
}


enum GitRepo {
    
    enum RepositoryLists {
        struct Request {
            
        }
        struct Response {
            let result: [Repository]
        }
        struct ViewModel {
            let result: [Repository]
        }
    }
}

